# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 09:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TNZListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_image', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('logo_image', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('gallery_images', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('unique_id', models.IntegerField()),
                ('market', models.CharField(max_length=5)),
                ('modified_date', models.DateTimeField(null=True)),
                ('listing_description', models.TextField()),
                ('listing_summary', models.TextField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('regionname', models.CharField(max_length=50)),
                ('business_type', models.CharField(max_length=200)),
                ('minimum_age', models.SmallIntegerField(null=True)),
                ('max_capacity', models.TextField()),
                ('website_link', models.TextField()),
                ('booking_link', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('operational_hours', models.TextField()),
                ('street', models.TextField()),
                ('suburb', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('proximity_to_town', models.TextField()),
                ('proximity_to_airport', models.TextField()),
                ('freephone', models.CharField(max_length=50)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('listing_types', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('booking_email', models.CharField(max_length=50)),
                ('cancellation_policy', models.TextField()),
                ('parking', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TNZRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('o_id', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('name_key', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TNZTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('o_id', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('listing_count', models.IntegerField()),
                ('name_key', models.CharField(max_length=200)),
                ('market', models.CharField(max_length=5)),
            ],
        ),
    ]
