# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzimageinstance',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='listings.TNZImage'),
        ),
        migrations.AlterField(
            model_name='tnzlisting',
            name='tags',
            field=models.ManyToManyField(related_name='listings', to='listings.TNZTag'),
        ),
    ]
