# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('unique_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
