# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20170118_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzimage',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
