# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rawlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawtag',
            name='data',
        ),
        migrations.AddField(
            model_name='rawtag',
            name='listing_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtag',
            name='market',
            field=models.CharField(default='en', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtag',
            name='o_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtag',
            name='unique_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
