# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20170118_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzimage',
            name='gallery_image_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='listings.TNZListing'),
        ),
    ]
