# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20161126_0451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawListing',
            new_name='TNZRawListing',
        ),
        migrations.RenameModel(
            old_name='RawTag',
            new_name='TNZTag',
        ),
    ]
