# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20170118_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzlisting',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
