# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20170120_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzlisting',
            name='logo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_image_listing', to='listings.TNZImage'),
        ),
        migrations.AlterField(
            model_name='tnzlisting',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image_listing', to='listings.TNZImage'),
        ),
    ]
