# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_tnzrawlisting_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnztag',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
