# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20170120_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzimage',
            name='credit',
            field=models.CharField(max_length=200),
        ),
    ]
