# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20170120_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzimage',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
