# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20161126_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnzrawlisting',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.TNZRegion'),
        ),
    ]
