# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_tnzrawlisting_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNZListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=200)),
                ('main_image', django.contrib.postgres.fields.jsonb.JSONField()),
                ('logo_image', django.contrib.postgres.fields.jsonb.JSONField()),
                ('gallery_images', django.contrib.postgres.fields.jsonb.JSONField()),
                ('unique_id', models.IntegerField()),
                ('market', models.CharField(max_length=5)),
                ('modified_date', models.DateTimeField()),
                ('listing_description', models.TextField()),
                ('listing_summary', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('business_type', models.CharField(max_length=200)),
                ('minimum_age', models.SmallIntegerField()),
                ('max_capacity', models.TextField()),
                ('website_link', models.TextField()),
                ('booking_link', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('operational_hours', models.TextField()),
                ('street', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.SmallIntegerField()),
                ('proximity_to_town', models.TextField()),
                ('proximity_to_airport', models.TextField()),
                ('freephone', models.CharField(max_length=50)),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField()),
                ('listing_types', django.contrib.postgres.fields.jsonb.JSONField()),
                ('booking_email', models.CharField(max_length=50)),
                ('cancellation_policy', models.TextField()),
                ('parking', models.TextField()),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.TNZRegion')),
            ],
        ),
        migrations.RemoveField(
            model_name='tnzrawlisting',
            name='region',
        ),
        migrations.DeleteModel(
            name='TNZRawListing',
        ),
    ]
