# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20170120_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnzimage',
            name='file',
            field=models.ImageField(null=True, upload_to='listings/'),
        ),
    ]
