# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_tnzimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnzimageinstance',
            name='image',
        ),
        migrations.DeleteModel(
            name='TNZImageInstance',
        ),
    ]
