# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20161127_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzlisting',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tnzlisting',
            name='postcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tnzlisting',
            name='suburb',
            field=models.CharField(max_length=50),
        ),
    ]
