# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20161127_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnzlisting',
            name='region',
        ),
    ]
