# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_remove_tnzlisting_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnzlisting',
            name='regionname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
