# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 10:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_tnzlisting_regionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzlisting',
            name='logo_image',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
