# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_auto_20161127_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzlisting',
            name='street',
            field=models.TextField(),
        ),
    ]
