# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20161211_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnzlisting',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tnzlisting',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
